<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [ ]:
subsetting - putting a list into a listXXX -> picking sth by index
indexing - putting a number from 0 to len() onto the item in listXX ->accessing things by position
slicing - cutting a string into parts seperated by a - or spave -> [start:stop:step]
masking -> boolean, true/false

In [2]:
import numpy as np

In [ ]:
Numbers = []
for item in np_array_2d:
    

darray.astype(int, copy=True, order='K', casting='unsafe', subok=True)


In [3]:
import numpy as np

In [ ]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers_np = np_array_2d[:,0].astype(int)

my_mask = numbers_np %2 != 0
print(sum(numbers_np[my_mask])) 

#to get the tuple
print(np_array_2d[my_mask])

#to get the letters only
print(np_array_2d[my_mask][:,1])


#print (np_array_2d[my_mask])
#for item in np_array_2d:
#    if int(item[0]) %2 != 0:
#        counted.append(item[1])
#print(counted)

    

25
[['1' 'A']
 ['3' 'C']
 ['5' 'E']
 ['7' 'G']
 ['9' 'I']]
['A' 'C' 'E' 'G' 'I']


In [36]:
np_numbers = np.array([[66, 50, 57, -1, -1], 
                       [92, -1, 88, -1, -1], 
                       [75, -1, -1, 76, -1], 
                       [-1, 51, 87, -1, -1], 
                       [71, -1, 67, -1, 69]])


mask_1 = np_numbers<50
np_numbers[mask_1] = -1

mask_2 = np_numbers >50
np_numbers[mask_2] = +1

mask_3 = np_numbers == 50
np_numbers[mask_3] = 0

print(np_numbers)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
