<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [3]:
import numpy as np

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [5]:
py_list

['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [24]:
py_list[6:-3]

#c3 at 2, e5 at 4

['g7']

In [27]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
mask = np_array//2
np_array[mask]

#how to count tbe number of truths using masks

array([1, 2, 2, 3, 3, 4, 4, 5, 5, 6])

In [47]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [46]:
np.logical_and(np_array > 3, np_array < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [33]:
np_array%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])


#how it work is that it find the item the index is linked to, then go fro minimum to maximum but not counting max in a FORWARD direction

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [52]:
py_list_2d = [[1, "A"], 
              [2, "B"], 
              [3, "C"], 
              [4, "D"],
              [5, "E"], 
              [6, "F"], 
              [7, "G"], 
              [8, "H"],
              [9, "I"], 
              [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [53]:
py_list_2d[3][1]

'D'

In [56]:
np_array_2d[3,0]

np.str_('4')

In [60]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [63]:
np_array_2d[:3,0]
#starts from the start, gives the FIRST element until it reached the index 2 

array(['1', '2', '3'], dtype='<U21')

In [61]:
np_array_2d[6]

array(['7', 'G'], dtype='<U21')

In [64]:
py_list_2d[3:6][0]
np_array_2d[3:6, 0]
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

In [65]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [70]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [69]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])
x
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

In [71]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

## Footnotes